services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: digg-service-api:latest
    ports:
      - "8080:8080"
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: digg-service-web:latest
    depends_on:
      - api
    ports:
      - "8081:80"
    networks:
      - appnet

networks:
  appnet: {}