spring:
  mvc:
    cors:
      mappings:
        "[/**]":
          allowed-origins: "http://localhost:8080,http://localhost:8081,http://localhost:5173"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful

logging:
  level:
    org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator: error