name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# Minimal perms; allow pushing container img
permissions:
  contents: read
  packages: write

# Cancel in-progress runs for same ref if new one starts
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend • Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Maven Test + Package
        run: mvn -B -ntp clean verify

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: |
            target/surefire-reports/**
            target/failsafe-reports/**
          if-no-files-found: ignore

      - name: Upload backend artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: |
            target/*.jar
          if-no-files-found: warn

  frontend:
    name: Frontend • Test & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps (ci if lockfile, else install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run unit tests with coverage
        run: npm run test:ci

      - name: Upload frontend coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: |
            frontend/coverage/**
          if-no-files-found: ignore

      - name: Build frontend
        run: npm run build

      - name: Upload frontend dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
          if-no-files-found: error

  docker:
    name: Docker • Build (and Push on main)
    runs-on: ubuntu-latest
    needs: [ backend, frontend ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login only for push events (PRs build but don't push)
      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Prepare lowercase image names
      - name: Prepare image names (lowercase)
        id: prep
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "BACKEND_IMAGE=ghcr.io/${REPO_LC}-backend" >> "$GITHUB_ENV"
          echo "FRONTEND_IMAGE=ghcr.io/${REPO_LC}-frontend" >> "$GITHUB_ENV"
          echo "FULLSTACK_IMAGE=ghcr.io/${REPO_LC}-fullstack" >> "$GITHUB_ENV"
          echo "SHA_TAG=sha-${{ github.sha }}" >> "$GITHUB_ENV"

      # Backend img
      - name: Build (and Push) Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          platforms: linux/amd64
          tags: |
            ${{ env.BACKEND_IMAGE }}:${{ env.SHA_TAG }}
            ${{ env.BACKEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Frontend img
      - name: Build (and Push) Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          platforms: linux/amd64
          tags: |
            ${{ env.FRONTEND_IMAGE }}:${{ env.SHA_TAG }}
            ${{ env.FRONTEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build (and Push) Fullstack Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.fullstack
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          platforms: linux/amd64
          tags: |
            ${{ env.FULLSTACK_IMAGE }}:${{ env.SHA_TAG }}
            ${{ env.FULLSTACK_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_URL=/api