name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Backend
        working-directory: ./backend
        run: mvn clean package
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      - name: Build Docker Images
        run: |
          docker build -t backend ./backend
          docker build -t frontend ./frontend
