name: SonarCloud analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read            # allow PR decoration
  security-events: write         # allow publishing to GitHub Code Scanning

jobs:
  analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # full history

      - name: Set up JDK 17 (required by SonarScanner)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Analyze with SonarCloud
        # You can pin a tag (e.g., @v2.2.0) or a commit for supply-chain safety
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: .
          args: >-
            -Dsonar.projectKey=Macweese_digg-service
            -Dsonar.organization=macweese
            # -Dsonar.sources=.
            # -Dsonar.tests=.
            # -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            # -Dsonar.coverage.exclusions=**/*.test.*,**/tests/**